version: '2.1'

services:
  web:
    image: balance-coop
    restart: unless-stopped
    build:
      context: .
    environment:
      STATIC_PATH: /app/client/dist
    volumes:
      - ./data:/app/data
      - ./config.yml:/app/cfg/config.yml
    ports:
      - 5000:5000/tcp
