version: '2.1'

services:
  web:
    image: balance-coop
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./data:/app/data
    env_file:
      - web.env
    ports:
      - 5000:5000/tcp
